title: Micro.blog Help
description: Documentation for Micro.blog.
url: https://help.micro.blog

author:
  name: Manton Reece
  url: https://manton.org

repo:
  url: https://github.com/microdotblog/help.micro.blog

icon: /assets/icons/icon.png
favicon: /assets/icons/favicon.png
theme_color: "#f80"

markdown: kramdown
permalink: /:year/:title/
sass:
  style: compressed

defaults:
- scope:
    path: ""
    type: pages
  values:
    layout: default
- scope:
    path: ""
    type: posts
  values:
    layout: post
- scope:
    path: ""
    type: drafts
  values:
    layout: post

exclude:
- CNAME
- Gemfile
- Gemfile.lock
- README.md
- thanks.md

jekyll-mentions:
  base_url: https://micro.blog

plugins:
  - jekyll-mentions
